name: publish package

on:
  push:
    branches: [ 'release' ]

permissions:
  contents: read
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '24.14.0'
      - run: npm install
      - run: npm run test
      - run: npm run build
      - run: npm config set @michahell:registry https://npm.pkg.github.com
      - run: echo "//npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}}" >> .npmrc
      - run: npm set "//npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}}"
      - run: npm publish --registry https://npm.pkg.github.com
