name: release

on:
  workflow_run:
    workflows: [ prepare release ]
    types:
      - completed

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: softprops/action-gh-release@v2
        with:
          files: './dist/chuckNorrisJokeGenerator/browser/**/*'
